# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: printer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='printer.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\021Web.PrinterClient'),
  serialized_pb=_b('\n\rprinter.proto\"4\n\x17PrintMedicationResponse\x12\x19\n\x11\x65xpected_duration\x18\x01 \x01(\x05\"g\n\x03ODF\x12\r\n\x05label\x18\x01 \x01(\t\x12\x11\n\tdrug_name\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x65nsity\x18\x03 \x01(\x02\x12\x0e\n\x06height\x18\x04 \x01(\x02\x12\r\n\x05width\x18\x05 \x01(\x02\x12\x0e\n\x06length\x18\x06 \x01(\x02\"+\n\x15\x43reatePrintJobRequest\x12\x12\n\x04odfs\x18\x01 \x03(\x0b\x32\x04.ODF\"C\n\x16\x43reatePrintjobResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x19\n\x11\x65xpected_duration\x18\x02 \x01(\x05\"$\n\x12RunPrintJobRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\":\n\x13RunPrintJobResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\nerror_code\x18\x02 \x01(\t\"%\n\x13GetJobStatusRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"\x88\x01\n\x14GetJobStatusResponse\x12/\n\x06status\x18\x01 \x01(\x0e\x32\x1f.GetJobStatusResponse.JobStatus\"?\n\tJobStatus\x12\t\n\x05READY\x10\x00\x12\x0c\n\x08PRINTING\x10\x01\x12\x0c\n\x08\x46INISHED\x10\x02\x12\x0b\n\x07REMOVED\x10\x03\"\x19\n\x17GetPrinterStatusRequest\"\x8f\x01\n\x18GetPrinterStatusResponse\x12\x37\n\x06status\x18\x01 \x01(\x0e\x32\'.GetPrinterStatusResponse.PrinterStatus\":\n\rPrinterStatus\x12\x08\n\x04IDLE\x10\x00\x12\x0c\n\x08PRINTING\x10\x01\x12\x11\n\rNO_CONNECTION\x10\x02\x32\x94\x02\n\x07Printer\x12\x43\n\x0e\x43reatePrintJob\x12\x16.CreatePrintJobRequest\x1a\x17.CreatePrintjobResponse\"\x00\x12:\n\x0bRunPrintJob\x12\x13.RunPrintJobRequest\x1a\x14.RunPrintJobResponse\"\x00\x12=\n\x0cGetJobStatus\x12\x14.GetJobStatusRequest\x1a\x15.GetJobStatusResponse\"\x00\x12I\n\x10GetPrinterStatus\x12\x18.GetPrinterStatusRequest\x1a\x19.GetPrinterStatusResponse\"\x00\x42\x14\xaa\x02\x11Web.PrinterClientb\x06proto3')
)



_GETJOBSTATUSRESPONSE_JOBSTATUS = _descriptor.EnumDescriptor(
  name='JobStatus',
  full_name='GetJobStatusResponse.JobStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='READY', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRINTING', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FINISHED', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REMOVED', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=501,
  serialized_end=564,
)
_sym_db.RegisterEnumDescriptor(_GETJOBSTATUSRESPONSE_JOBSTATUS)

_GETPRINTERSTATUSRESPONSE_PRINTERSTATUS = _descriptor.EnumDescriptor(
  name='PrinterStatus',
  full_name='GetPrinterStatusResponse.PrinterStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IDLE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRINTING', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_CONNECTION', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=679,
  serialized_end=737,
)
_sym_db.RegisterEnumDescriptor(_GETPRINTERSTATUSRESPONSE_PRINTERSTATUS)


_PRINTMEDICATIONRESPONSE = _descriptor.Descriptor(
  name='PrintMedicationResponse',
  full_name='PrintMedicationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='expected_duration', full_name='PrintMedicationResponse.expected_duration', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=69,
)


_ODF = _descriptor.Descriptor(
  name='ODF',
  full_name='ODF',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='ODF.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='drug_name', full_name='ODF.drug_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='density', full_name='ODF.density', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='ODF.height', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='ODF.width', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length', full_name='ODF.length', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=174,
)


_CREATEPRINTJOBREQUEST = _descriptor.Descriptor(
  name='CreatePrintJobRequest',
  full_name='CreatePrintJobRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='odfs', full_name='CreatePrintJobRequest.odfs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=219,
)


_CREATEPRINTJOBRESPONSE = _descriptor.Descriptor(
  name='CreatePrintjobResponse',
  full_name='CreatePrintjobResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_id', full_name='CreatePrintjobResponse.job_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expected_duration', full_name='CreatePrintjobResponse.expected_duration', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=288,
)


_RUNPRINTJOBREQUEST = _descriptor.Descriptor(
  name='RunPrintJobRequest',
  full_name='RunPrintJobRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_id', full_name='RunPrintJobRequest.job_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=290,
  serialized_end=326,
)


_RUNPRINTJOBRESPONSE = _descriptor.Descriptor(
  name='RunPrintJobResponse',
  full_name='RunPrintJobResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='RunPrintJobResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='RunPrintJobResponse.error_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=386,
)


_GETJOBSTATUSREQUEST = _descriptor.Descriptor(
  name='GetJobStatusRequest',
  full_name='GetJobStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_id', full_name='GetJobStatusRequest.job_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=388,
  serialized_end=425,
)


_GETJOBSTATUSRESPONSE = _descriptor.Descriptor(
  name='GetJobStatusResponse',
  full_name='GetJobStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='GetJobStatusResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GETJOBSTATUSRESPONSE_JOBSTATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=428,
  serialized_end=564,
)


_GETPRINTERSTATUSREQUEST = _descriptor.Descriptor(
  name='GetPrinterStatusRequest',
  full_name='GetPrinterStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=566,
  serialized_end=591,
)


_GETPRINTERSTATUSRESPONSE = _descriptor.Descriptor(
  name='GetPrinterStatusResponse',
  full_name='GetPrinterStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='GetPrinterStatusResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GETPRINTERSTATUSRESPONSE_PRINTERSTATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=594,
  serialized_end=737,
)

_CREATEPRINTJOBREQUEST.fields_by_name['odfs'].message_type = _ODF
_GETJOBSTATUSRESPONSE.fields_by_name['status'].enum_type = _GETJOBSTATUSRESPONSE_JOBSTATUS
_GETJOBSTATUSRESPONSE_JOBSTATUS.containing_type = _GETJOBSTATUSRESPONSE
_GETPRINTERSTATUSRESPONSE.fields_by_name['status'].enum_type = _GETPRINTERSTATUSRESPONSE_PRINTERSTATUS
_GETPRINTERSTATUSRESPONSE_PRINTERSTATUS.containing_type = _GETPRINTERSTATUSRESPONSE
DESCRIPTOR.message_types_by_name['PrintMedicationResponse'] = _PRINTMEDICATIONRESPONSE
DESCRIPTOR.message_types_by_name['ODF'] = _ODF
DESCRIPTOR.message_types_by_name['CreatePrintJobRequest'] = _CREATEPRINTJOBREQUEST
DESCRIPTOR.message_types_by_name['CreatePrintjobResponse'] = _CREATEPRINTJOBRESPONSE
DESCRIPTOR.message_types_by_name['RunPrintJobRequest'] = _RUNPRINTJOBREQUEST
DESCRIPTOR.message_types_by_name['RunPrintJobResponse'] = _RUNPRINTJOBRESPONSE
DESCRIPTOR.message_types_by_name['GetJobStatusRequest'] = _GETJOBSTATUSREQUEST
DESCRIPTOR.message_types_by_name['GetJobStatusResponse'] = _GETJOBSTATUSRESPONSE
DESCRIPTOR.message_types_by_name['GetPrinterStatusRequest'] = _GETPRINTERSTATUSREQUEST
DESCRIPTOR.message_types_by_name['GetPrinterStatusResponse'] = _GETPRINTERSTATUSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PrintMedicationResponse = _reflection.GeneratedProtocolMessageType('PrintMedicationResponse', (_message.Message,), {
  'DESCRIPTOR' : _PRINTMEDICATIONRESPONSE,
  '__module__' : 'printer_pb2'
  # @@protoc_insertion_point(class_scope:PrintMedicationResponse)
  })
_sym_db.RegisterMessage(PrintMedicationResponse)

ODF = _reflection.GeneratedProtocolMessageType('ODF', (_message.Message,), {
  'DESCRIPTOR' : _ODF,
  '__module__' : 'printer_pb2'
  # @@protoc_insertion_point(class_scope:ODF)
  })
_sym_db.RegisterMessage(ODF)

CreatePrintJobRequest = _reflection.GeneratedProtocolMessageType('CreatePrintJobRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEPRINTJOBREQUEST,
  '__module__' : 'printer_pb2'
  # @@protoc_insertion_point(class_scope:CreatePrintJobRequest)
  })
_sym_db.RegisterMessage(CreatePrintJobRequest)

CreatePrintjobResponse = _reflection.GeneratedProtocolMessageType('CreatePrintjobResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEPRINTJOBRESPONSE,
  '__module__' : 'printer_pb2'
  # @@protoc_insertion_point(class_scope:CreatePrintjobResponse)
  })
_sym_db.RegisterMessage(CreatePrintjobResponse)

RunPrintJobRequest = _reflection.GeneratedProtocolMessageType('RunPrintJobRequest', (_message.Message,), {
  'DESCRIPTOR' : _RUNPRINTJOBREQUEST,
  '__module__' : 'printer_pb2'
  # @@protoc_insertion_point(class_scope:RunPrintJobRequest)
  })
_sym_db.RegisterMessage(RunPrintJobRequest)

RunPrintJobResponse = _reflection.GeneratedProtocolMessageType('RunPrintJobResponse', (_message.Message,), {
  'DESCRIPTOR' : _RUNPRINTJOBRESPONSE,
  '__module__' : 'printer_pb2'
  # @@protoc_insertion_point(class_scope:RunPrintJobResponse)
  })
_sym_db.RegisterMessage(RunPrintJobResponse)

GetJobStatusRequest = _reflection.GeneratedProtocolMessageType('GetJobStatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETJOBSTATUSREQUEST,
  '__module__' : 'printer_pb2'
  # @@protoc_insertion_point(class_scope:GetJobStatusRequest)
  })
_sym_db.RegisterMessage(GetJobStatusRequest)

GetJobStatusResponse = _reflection.GeneratedProtocolMessageType('GetJobStatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETJOBSTATUSRESPONSE,
  '__module__' : 'printer_pb2'
  # @@protoc_insertion_point(class_scope:GetJobStatusResponse)
  })
_sym_db.RegisterMessage(GetJobStatusResponse)

GetPrinterStatusRequest = _reflection.GeneratedProtocolMessageType('GetPrinterStatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPRINTERSTATUSREQUEST,
  '__module__' : 'printer_pb2'
  # @@protoc_insertion_point(class_scope:GetPrinterStatusRequest)
  })
_sym_db.RegisterMessage(GetPrinterStatusRequest)

GetPrinterStatusResponse = _reflection.GeneratedProtocolMessageType('GetPrinterStatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETPRINTERSTATUSRESPONSE,
  '__module__' : 'printer_pb2'
  # @@protoc_insertion_point(class_scope:GetPrinterStatusResponse)
  })
_sym_db.RegisterMessage(GetPrinterStatusResponse)


DESCRIPTOR._options = None

_PRINTER = _descriptor.ServiceDescriptor(
  name='Printer',
  full_name='Printer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=740,
  serialized_end=1016,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreatePrintJob',
    full_name='Printer.CreatePrintJob',
    index=0,
    containing_service=None,
    input_type=_CREATEPRINTJOBREQUEST,
    output_type=_CREATEPRINTJOBRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RunPrintJob',
    full_name='Printer.RunPrintJob',
    index=1,
    containing_service=None,
    input_type=_RUNPRINTJOBREQUEST,
    output_type=_RUNPRINTJOBRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetJobStatus',
    full_name='Printer.GetJobStatus',
    index=2,
    containing_service=None,
    input_type=_GETJOBSTATUSREQUEST,
    output_type=_GETJOBSTATUSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetPrinterStatus',
    full_name='Printer.GetPrinterStatus',
    index=3,
    containing_service=None,
    input_type=_GETPRINTERSTATUSREQUEST,
    output_type=_GETPRINTERSTATUSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRINTER)

DESCRIPTOR.services_by_name['Printer'] = _PRINTER

# @@protoc_insertion_point(module_scope)
