# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import printer_pb2 as printer__pb2


class PrinterStub(object):
  """Service for interacting with the Dispenser
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreatePrintJob = channel.unary_unary(
        '/Printer/CreatePrintJob',
        request_serializer=printer__pb2.CreatePrintJobRequest.SerializeToString,
        response_deserializer=printer__pb2.CreatePrintjobResponse.FromString,
        )
    self.RunPrintJob = channel.unary_unary(
        '/Printer/RunPrintJob',
        request_serializer=printer__pb2.RunPrintJobRequest.SerializeToString,
        response_deserializer=printer__pb2.RunPrintJobResponse.FromString,
        )
    self.GetJobStatus = channel.unary_unary(
        '/Printer/GetJobStatus',
        request_serializer=printer__pb2.GetJobStatusRequest.SerializeToString,
        response_deserializer=printer__pb2.GetJobStatusResponse.FromString,
        )
    self.GetPrinterStatus = channel.unary_unary(
        '/Printer/GetPrinterStatus',
        request_serializer=printer__pb2.GetPrinterStatusRequest.SerializeToString,
        response_deserializer=printer__pb2.GetPrinterStatusResponse.FromString,
        )


class PrinterServicer(object):
  """Service for interacting with the Dispenser
  """

  def CreatePrintJob(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RunPrintJob(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetJobStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPrinterStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PrinterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreatePrintJob': grpc.unary_unary_rpc_method_handler(
          servicer.CreatePrintJob,
          request_deserializer=printer__pb2.CreatePrintJobRequest.FromString,
          response_serializer=printer__pb2.CreatePrintjobResponse.SerializeToString,
      ),
      'RunPrintJob': grpc.unary_unary_rpc_method_handler(
          servicer.RunPrintJob,
          request_deserializer=printer__pb2.RunPrintJobRequest.FromString,
          response_serializer=printer__pb2.RunPrintJobResponse.SerializeToString,
      ),
      'GetJobStatus': grpc.unary_unary_rpc_method_handler(
          servicer.GetJobStatus,
          request_deserializer=printer__pb2.GetJobStatusRequest.FromString,
          response_serializer=printer__pb2.GetJobStatusResponse.SerializeToString,
      ),
      'GetPrinterStatus': grpc.unary_unary_rpc_method_handler(
          servicer.GetPrinterStatus,
          request_deserializer=printer__pb2.GetPrinterStatusRequest.FromString,
          response_serializer=printer__pb2.GetPrinterStatusResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Printer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
